- name: setup todo project
  hosts: all
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: Install nodejs
      apt:
        name: nodejs
        state: present
    - name: Install npm
      apt:
        name: npm
        state: present
