    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: Install nodejs
      apt:
        name: nodejs
        state: present
    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Removing default files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/sites-available/default
        - /etc/nginx/sites-enabled/default
        - /var/www/html/index.nginx-debian.html

    - name: create a vue directory
      file:
        path: /var/www/html/vue
        state: directory

    - name: create frontend directory
      file:
        path: /var/www/html/vue/frontend
        state: directory

    - name: Download Artifacts from Nexus
      get_url:
        url: http://3.91.2.242:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
        dest: /tmp/frontend.zip
        username: admin
        password: Omkar@123

    - name: unzip the downloaded content
      unarchive:
        src: /tmp/frontend.zip
        dest: /var/www/html/vue/frontend
        remote_src: yes

    - name: Copy default config file to sites enabled
      template:
        src: default.config
        dest: /etc/nginx/sites-enabled/default.config
        remote_src: yes

    - name: Start service
      systemd:
        name: nginx
        state: started
        enabled: yes